#!/usr/bin/env bash
# This script creates a pid file, handles signals, and deletes the pid file upon termination

echo $$ > /var/run/myscript.pid

handle_sigint() {
    echo "Y U no love me?!"
}

handle_sigterm() {
    echo "I hate the kill command"
    rm /var/run/myscript.pid
    exit 0
}

handle_sigquit() {
    rm /var/run/myscript.pid
    exit 0
}

trap 'handle_sigint' SIGINT
trap 'handle_sigterm' SIGTERM
trap 'handle_sigquit' SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 2
done
