#!/usr/bin/env bash
# Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

for varfile in *; do
  echo "$varfile" | cut -d '-' -f 2-
done
