#!/usr/bin/env bash
# Bash script that gives you information about the school file.

# Requirements:

# You must use if and, else (case is forbidden)
# Your Bash script should check if the file exists and print:
# if the file exists: school file exists
# if the file does not exist: school file does not exist
# If the file exists, print:
# if the file is empty: school file is empty
# if the file is not empty: school file is not empty
# if the file is a regular file: school is a regular file
# if the file is not a regular file: (nothing)

varF="school"

if [ -e "$varF" ]; then
  echo "$varF file exists"
  if [ -s "$varF" ]; then
    echo "$varF file is not empty"
  else
    echo "$varF file is empty"
  fi
  if [ -f "$varF" ]; then
    echo "$varF is a regular file"
  fi
else
  echo "$varF file does not exist"
fi
